require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'SightStudy' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  pod 'RCTSystemSetting', :path => '../node_modules/react-native-system-setting'

  pod 'RNPermissions', :path => '../node_modules/react-native-permissions'

  pod 'react-native-voice', :path => '../node_modules/@react-native-voice/voice'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  pod 'TextToSpeech', :path => '../node_modules/react-native-tts'

  target 'SightStudyTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
  end
end